### Section 2. N차원 배열의 인덱싱

In [1]:
import numpy as np

#### 2-1. 배열의 index 접근하기

In [8]:
# 1차원 배열
arr = np.arange(10)
print(arr)
print(arr[3])
print(arr[1])
print(arr[9])
print(arr[-1])
print(arr[-3])
print(arr[-10])

[0 1 2 3 4 5 6 7 8 9]
3
1
9
9
7
0


In [12]:
# 2차원 배열
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr, arr.shape, arr.ndim)
print('\n')
print(arr[0][3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


4


In [17]:
arr = np.arange(10)
print(arr[3:8])
print(arr[3:])
print(arr[:7])
print(arr[:-1])
print(arr[:])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]


In [22]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr[0, :]) # 0행의 모든 원소을 출력함
print('\n')

print(arr[:, 1]) # 1열의 모든 원소를 출력함 
print('\n')

print(arr[:3, :]) # 0부터 3행까지의 모든 열을 출력
print('\n')

print(arr[:2, 2:]) # 0부터 2행까지의 2열부터 출력

[1 2 3 4]


[ 2  6 10]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[3 4]
 [7 8]]


#### Section 2. N차원 배열의 인덱싱

In [25]:
# 1차원 배열
arr = np.array([5,10,15,20,25,30])
print(arr[[0,2,4]])

[ 5 15 25]


In [28]:
# 2차원 배열
arr = np.array([[5, 10, 15, 20],
               [25, 30, 35, 40],
               [45, 50, 55, 60]])

print(arr[[0, 2], 2:]) # 0~2행부터, 2열부터 끝까지 원소를 출력
print('\n')

print(arr[1:, [2, 3]]) # 1행부터 끝까지부터 2~3열의 원소를 출력

[[15 20]
 [55 60]]


[[35 40]
 [55 60]]


#### 2-3. 배열의 Boolean 인덱싱

In [30]:
arr = np.array([1,2,3,4])
print(arr[[True, False, True, False]])

[1 3]


In [33]:
arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print(arr[[True, False], True])
print('\n')

print(arr[arr > 4]) # 4보다 큰 원소를 출력
print(arr[arr <= 2]) # 2이하의 원소를 출력

[[1 2 3 4]]


[5 6 7 8]
[1 2]
