### Section 3. N차원 배열의 연산법

In [2]:
import numpy as np

#### 3-1. 배열의 연산1 : 사칙연산/제곱/제곱근/몫/나머지

In [3]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


arr2 = np.array([[2,2,2],
                 [2,2,2],
                 [2,2,2]])

print(arr1)
print('\n')
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
# 덧셈
print(arr1 + arr2)
print('\n')

print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# 뺄샘
print(arr1 - arr2)
print('\n')

print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [6]:
# 곱셈
print(arr1 * arr2)
print('\n')

print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
# 나눗셈
print(arr1 / arr2)
print('\n')

print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [8]:
# 제곱
print(arr1 ** 5)
print('\n')

print(np.square(arr1, arr2))

[[    1    32   243]
 [ 1024  3125  7776]
 [16807 32768 59049]]


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [9]:
# 제곱근
print(np.sqrt(arr1))
print('\n')
print(np.sqrt(arr2))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
# 몫
print(arr1 // 2)

print('\n')

# 나머지
print(arr1 & 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


[[0 2 2]
 [0 0 2]
 [2 0 0]]


#### 3-2. 배열의 연산2 : 내적/절댓값/올림/내림/반올림/버림

In [11]:
# 1차원 행렬
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])

print(np.dot(arr1, arr2)) # 각각의 원소의 곱의 합을 반환 : 1*2 + 3*2 + 4*3 = 20

20


In [12]:
# 2차원 행렬
arr1 = np.array([[1,2],
                [4,5]])

arr2 = np.array([[1,2],
                [0,3]])

print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


In [13]:
# 절댓값
arr1 = np.array([[1, -2],
                [-4, 5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [14]:
# 올림
arr1 = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])
print(np.ceil(arr1))
print('\n')

# 내림
print(np.floor(arr1))
print('\n')

# 반올림
print(np.round(arr1))
print('\n')

# 버림
print(np.trunc(arr1))

[[ 2. -2.]
 [-4.  6.]]


[[ 1. -3.]
 [-5.  5.]]


[[ 2. -2.]
 [-4.  5.]]


[[ 1. -2.]
 [-4.  5.]]


#### 3-3. 배열의 연산3 : 최소값/최대값/합계/평균/표준편차/누적값

In [15]:
arr = np.array([[1,2,3],
               [0,1,4]])

In [16]:
# 최소값
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0)) # 각 열의 최솟값을 반환
print(arr.min(axis=1)) # 각 행의 최솟값을 반환

0
0
[0 1 3]
[1 0]


In [17]:
# 최대값
print(np.max(arr))
print(arr.max())
print(arr.max(axis=0)) # 각 열의 최대값을 반환
print(arr.max(axis=1)) # 각 행의 최대값을 반환

4
4
[1 2 4]
[3 4]


In [20]:
# 합계
print(np.sum(arr))
print(arr.sum(axis=0)) # 각 열의 합계를 반환
print(arr.sum(axis=1)) # 각 행의 합계를 반환

11
[1 3 7]
[6 5]


In [21]:
# 평균
print(np.mean(arr))
print(arr.mean(axis=0)) # 각 열의 평균을 반환
print(arr.mean(axis=1)) # 각 행의 평균을 반환

1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]


In [22]:
# 표준편차
print(np.std(arr))
print(arr.std(axis=0)) # 각 열의 표준편차를 반환
print(arr.std(axis=1)) # 각 행의 표준편차를 반환

1.343709624716425
[0.5 0.5 0.5]
[0.81649658 1.69967317]


In [26]:
# 누적값
arr = np.array([[1,2,3],
                [0,1,4]])

print(np.cumsum(arr))
print('\n')

print(arr.cumsum())
print('\n')

print(arr.cumsum(axis=0)) # 각 열을 더한 누적값를 반환
print('\n')

print(arr.cumsum(axis=1)) # 각 행을 더한 누적값를 반환

[ 1  3  6  6  7 11]


[ 1  3  6  6  7 11]


[[1 2 3]
 [1 3 7]]


[[1 3 6]
 [0 1 5]]


In [29]:
# 중앙값
arr = np.array([[1,2,3],
                [0,1,4],
                [1,5,2]])

print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

[1. 2. 3.]
[2. 1. 2.]


#### 3-4 배열의 연산3 : 비교 연산 / 삼각함수

In [31]:
arr1 = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[1,0,3],
                [4,-2,9]])

# 비교연산자
print(arr1 == arr2) # 각각의 원소가 동일하면 True 아니면 False
print('\n')

print(arr1 > arr2) 
print('\n')

# array_equal()
print(np.array_equal(arr1, arr2))

[[ True False  True]
 [ True False False]]


[[False  True False]
 [False  True False]]


False


In [33]:
# 삼각 함수
arr = np.array([[1,2,3],
                [4,5,6]])

# sin()
print(np.sin(arr))
print('\n')

# cos()
print(np.cos(arr))
print('\n')

# tan()
print(np.tan(arr))
print('\n')

# pi()
print(np.pi)


[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


3.141592653589793


#### 3-5 BroadCasting
두 행렬의 연산을 위해 행렬 하나 혹은 두개가 정방행렬에 맞춰 원소값과 함께 확장하는 개념

In [34]:
arr1 = np.array([[0,0,0],
                [1,1,1],
                [2,2,2]])

arr2 = np.array([[5,6,7]])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [36]:
arr1 = np.array([[1,1,1]])

arr2 = np.array([[0],
                 [1],
                 [2]])

print(arr1 + arr2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


#### 3-6 벡터 연산의 장점

In [43]:
import time

In [44]:
arr = np.arange(99999999)

sum = 0
before = time.time()

for i in arr:
    sum += i
after = time.time()
print(sum, after - before, "초")

C:\Users\AISW-203-105\AppData\Local\Temp\ipykernel_10012\1850315838.py:7: RuntimeWarning: overflow encountered in long_scalars
  sum += i


787459713 16.45161747932434 초


In [45]:
# 벡터연산 : 시간을 단축해서 계산 가능하다.
before - time.time()
sum = np.sum(arr)
after = time.time()

print(sum, after - before, '초') 

787459713 16.513482809066772 초


In [48]:
arr1 = np.arange(9999999)
arr2 = np.arange(9999999)

In [49]:
sum = 0
before = time.time()

for i, j in zip(arr1, arr2):
    sum += i * j
    
after = time.time()
print(sum, after-before,'초')

C:\Users\AISW-203-105\AppData\Local\Temp\ipykernel_10012\166561633.py:5: RuntimeWarning: overflow encountered in long_scalars
  sum += i * j


-1295478593 11.204035520553589 초


In [50]:
# 벡터 연산
before = time.time() # 
sum = np.dot(arr1, arr2)
after = time.time()
print(sum, after-before, '초')

-1295478593 0.007977008819580078 초
