In [1]:
import numpy as np

#### 4-1 1차원 배열의 정렬

In [2]:
arr = np.random.randint(10, size=10)
print(arr)

[9 9 3 0 9 1 8 2 7 7]


In [5]:
print(np.sort(arr)) # 정렬
print(np.sort(arr)[::-1]) # 역순 정렬

[0 1 2 3 7 7 8 9 9 9]
[9 9 9 8 7 7 3 2 1 0]


In [7]:
arr = np.sort(arr)
print(arr)
print('\n')

arr.sort()
print(arr)

[0 1 2 3 7 7 8 9 9 9]


[0 1 2 3 7 7 8 9 9 9]


#### 4-2 2차원 배열의 정렬

In [8]:
arr = np.random.randint(15, size=(3,4))
print(arr)

[[ 2  5  3  6]
 [ 2  8  2 11]
 [13  7 12  3]]


In [11]:
print(np.sort(arr, axis=0)) # 원소가 오름차순 정렬
print('\n')

print(np.sort(arr, axis=None)) # 2차원 -> 1차원 변경 후 오름차순 정렬

[[ 2  5  2  3]
 [ 2  7  3  6]
 [13  8 12 11]]


[ 2  2  2  3  3  5  6  7  8 11 12 13]


In [12]:
# argsort() : 정렬된 원소의 원래 배열의 인덱스를 반환한다.
print(np.sort(arr, axis=1))
print('\n')

print(np.argsort(arr, axis=1)) # 행을 기준으로 원래 인덱스를 반환한다. 

[[ 2  3  5  6]
 [ 2  2  8 11]
 [ 3  7 12 13]]


[[0 2 1 3]
 [0 2 1 3]
 [3 1 2 0]]


In [14]:
# argsort() : 정렬된 원소의 원래 배열의 인덱스를 반환한다.
print(np.sort(arr, axis=0))
print('\n')

print(np.argsort(arr, axis=0)) # 열을 기준으로 원래 인덱스를 반환한다. 

[[ 2  5  2  3]
 [ 2  7  3  6]
 [13  8 12 11]]


[[0 0 1 2]
 [1 2 0 0]
 [2 1 2 1]]
