In [2]:
import numpy as np

#### 5-1 배열의 형태 변경1 : reshape()

In [3]:
arr = np.arange(12)
print(arr, arr.ndim)
print('\n')

arr = arr.reshape((3, 4)) # 원소의 갯수에 맞게 크기를 지정해야한다.
print(arr, arr.ndim)
print('\n')

arr = arr.reshape((2, 3, 2))
print(arr, arr.ndim)
print('\n')

arr = arr.reshape((2,2,1,3))
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3


[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


In [4]:
arr = np.arange(1, 13)
print(arr)
print('\n')

arr = arr.reshape(3, -1) # -1은 자동으로 배열을 적용한다.
print(arr)
print('\n')

arr = arr.reshape(3, 2, -1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


#### 5-2 배열의 형태 변경2 : resize(), ravel()

In [5]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
arr.resize(3, 4) # 3 by 4로 만들어준다.
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
arr = arr.ravel() # 2차원 배열을 1차원으로 변경시킨다.
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### 5-3 배열의 형태 변경3 : expand_dims(), squeeze()

In [18]:
# expand_dims() : 입력한 axis값을 기준으로 차원을 추가하는 함수
arr = np.array([1, 2])
print(arr, arr.shape)
print('\n')

arr = np.expand_dims(arr, axis=0)
print(arr, arr.shape)
print('\n')

arr = np.expand_dims(arr, axis=0)
print(arr, arr.shape)

[1 2] (2,)


[[1 2]] (1, 2)


[[[1 2]]] (1, 1, 2)


In [24]:
# squeeze() : 배열의 축을 제거해서 한차원씩 차원을 축소하는 함수
arr = np.array([[1, 2]])
print(arr, arr.shape, arr.ndim)
print('\n')

arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)
print('\n')

arr = np.array([[[1],
                [2],
                [3]]])

print(arr, arr.shape, arr.ndim)
print('\n')

arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

[[1 2]] (1, 2) 2


[1 2] (2,) 1


[[[1]
  [2]
  [3]]] (1, 3, 1) 3


[[1]
 [2]
 [3]] (3, 1) 2


In [28]:
arr = np.array([[[1,2,3]]])
print(arr, arr.shape, arr.ndim)
print('\n')

arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3


[[1 2 3]] (1, 3) 2


#### 5-4 전치행렬(Transpose)

In [35]:
arr = np.array([[1,2],
               [3,4]])
print(arr.T)
print('\n')
print(np.transpose(arr))
print('\n')

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr.T)
print('\n')
print(np.transpose(arr))
print('\n')

arr = np.array([[1,2],
                [4,5],
                [7,8]])

print(arr.T)
print('\n')
print(np.transpose(arr))

[[1 3]
 [2 4]]


[[1 3]
 [2 4]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


[[1 4 7]
 [2 5 8]]


[[1 4 7]
 [2 5 8]]


In [37]:
arr1 = np.array([[1,2],
                [4,5],
                [7,8]])
arr2 = np.full((3, 2), 2)

print((arr.T).dot(arr2))

[[24 24]
 [30 30]]
