In [1]:
import numpy as np

#### 6-1. 배열에 원소 추가 및 삭제

In [2]:
arr = [1,2,3,4,5,6,7,8]
arr.insert(2, 50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]


In [4]:
# 1차원 배열
arr = np.arange(1, 9)
arr = np.insert(arr, 2, 50)
print(arr)

[ 1  2 50  3  4  5  6  7  8]


In [5]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=0) # 행 기준 삽입
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]


In [6]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=1) # 행 기준 삽입
print(arr)

[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]


In [12]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=None) # 1차원으로 변경 후 삽입 
print(arr)

[ 1  2 50  3  4  5  6  7  8  9 10 11 12]


In [13]:
# delete()
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print('\n')

arr = np.delete(arr, 2, axis=0) # 행 기준 삭제
print(arr)
print('\n')

arr = np.delete(arr, 2, axis=1) # 행 기준 삭제
print(arr)
print('\n')

arr = np.delete(arr, 2, axis=None) # 1차원으로 변경 후 삭제
print(arr)
print('\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[1 2 3 4]
 [5 6 7 8]]


[[1 2 4]
 [5 6 8]]


[1 2 5 6 8]




#### 6-2 배열 간의 병합

In [21]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print(arr1)
print('\n')
print(arr2)
print('\n')

# axis = 0
arr3 = np.append(arr1, arr2, axis=0) # 배열 병합(행 기준)
print(arr3, end='\n\n')

# axis = 1
arr3 = np.append(arr1, arr2, axis=1) # 배열 병합(열 기준)
print(arr3, end='\n\n')

# axis = None
arr3 = np.append(arr1, arr2, axis=None) # 배열 병합(1차원 변경 후 기준)
print(arr3, end='\n\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [26]:
# vstack(), hstack()
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.vstack((arr1, arr2)) # 2차원 배열을 axis=0을 기준으로 병합
print(arr3)
print('\n')

arr3 = np.hstack((arr1, arr2)) # 2차원 배열을 axis=1을 기준으로 병합
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [28]:
# concatenate() : axis 값을 기준으로 두 행렬을 병합하는 함수이다.
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3)
print('\n')

arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### 6-3 배열의 분할

In [31]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print('\n')

# vsplit() : axis=0을 기준으로 배열을 분할
arr_vsplit = np.vsplit(arr, 3)
print(arr_vsplit)
print('\n')

# hsplit() : axis=1을 기준으로 배열을 분할
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [32]:
# 3차원 배열
arr = np.random.randint(0, 10, (4, 6, 8))
print(arr)

[[[7 3 1 2 2 2 5 5]
  [7 3 0 6 5 4 0 3]
  [7 4 6 6 6 7 3 7]
  [6 4 9 1 1 5 6 1]
  [4 2 7 2 2 9 0 6]
  [9 9 3 8 0 6 8 2]]

 [[0 8 5 9 3 3 5 7]
  [7 0 6 9 7 8 1 0]
  [5 7 5 3 4 5 0 2]
  [1 2 8 0 0 1 4 5]
  [6 8 7 0 9 6 1 8]
  [0 8 4 1 0 9 1 3]]

 [[7 5 7 2 0 6 8 6]
  [7 3 9 0 2 6 9 4]
  [4 1 2 7 8 2 8 0]
  [9 7 0 7 8 9 4 4]
  [8 8 4 0 3 5 7 2]
  [5 7 3 3 1 9 6 6]]

 [[8 4 0 0 5 3 3 3]
  [2 3 0 1 7 9 6 2]
  [7 8 8 1 0 7 7 7]
  [7 8 4 3 7 7 2 5]
  [4 2 0 9 5 2 8 6]
  [1 1 3 9 2 2 1 9]]]


In [36]:
arr_vsplit = np.vsplit(arr, 2)
print(arr_vsplit)

[array([[[7, 3, 1, 2, 2, 2, 5, 5],
        [7, 3, 0, 6, 5, 4, 0, 3],
        [7, 4, 6, 6, 6, 7, 3, 7],
        [6, 4, 9, 1, 1, 5, 6, 1],
        [4, 2, 7, 2, 2, 9, 0, 6],
        [9, 9, 3, 8, 0, 6, 8, 2]],

       [[0, 8, 5, 9, 3, 3, 5, 7],
        [7, 0, 6, 9, 7, 8, 1, 0],
        [5, 7, 5, 3, 4, 5, 0, 2],
        [1, 2, 8, 0, 0, 1, 4, 5],
        [6, 8, 7, 0, 9, 6, 1, 8],
        [0, 8, 4, 1, 0, 9, 1, 3]]]), array([[[7, 5, 7, 2, 0, 6, 8, 6],
        [7, 3, 9, 0, 2, 6, 9, 4],
        [4, 1, 2, 7, 8, 2, 8, 0],
        [9, 7, 0, 7, 8, 9, 4, 4],
        [8, 8, 4, 0, 3, 5, 7, 2],
        [5, 7, 3, 3, 1, 9, 6, 6]],

       [[8, 4, 0, 0, 5, 3, 3, 3],
        [2, 3, 0, 1, 7, 9, 6, 2],
        [7, 8, 8, 1, 0, 7, 7, 7],
        [7, 8, 4, 3, 7, 7, 2, 5],
        [4, 2, 0, 9, 5, 2, 8, 6],
        [1, 1, 3, 9, 2, 2, 1, 9]]])]


In [37]:
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit)

[array([[[7, 3, 1, 2, 2, 2, 5, 5],
        [7, 3, 0, 6, 5, 4, 0, 3],
        [7, 4, 6, 6, 6, 7, 3, 7]],

       [[0, 8, 5, 9, 3, 3, 5, 7],
        [7, 0, 6, 9, 7, 8, 1, 0],
        [5, 7, 5, 3, 4, 5, 0, 2]],

       [[7, 5, 7, 2, 0, 6, 8, 6],
        [7, 3, 9, 0, 2, 6, 9, 4],
        [4, 1, 2, 7, 8, 2, 8, 0]],

       [[8, 4, 0, 0, 5, 3, 3, 3],
        [2, 3, 0, 1, 7, 9, 6, 2],
        [7, 8, 8, 1, 0, 7, 7, 7]]]), array([[[6, 4, 9, 1, 1, 5, 6, 1],
        [4, 2, 7, 2, 2, 9, 0, 6],
        [9, 9, 3, 8, 0, 6, 8, 2]],

       [[1, 2, 8, 0, 0, 1, 4, 5],
        [6, 8, 7, 0, 9, 6, 1, 8],
        [0, 8, 4, 1, 0, 9, 1, 3]],

       [[9, 7, 0, 7, 8, 9, 4, 4],
        [8, 8, 4, 0, 3, 5, 7, 2],
        [5, 7, 3, 3, 1, 9, 6, 6]],

       [[7, 8, 4, 3, 7, 7, 2, 5],
        [4, 2, 0, 9, 5, 2, 8, 6],
        [1, 1, 3, 9, 2, 2, 1, 9]]])]
